#!/usr/bin/env bash

: '
ctheme - Change Theme

Will change the theme of the following at the same time:
	1. NeoVim
	2. Vim
	3. Alacritty
'

# ANSI color code variables
red="\e[0;31m"
green="\e[0;32m"
bold="\e[1m"
reset="\e[0m"

# Make sure user provides the theme name
if [[ ! $1 ]]; then
	echo -e "${red}${bold}ERROR: Theme name not provided.${reset}"
	exit 1
fi

# Make sure we take only one argument
if [[ $# -gt 1 ]]; then
	echo -e "${red}${bold}ERROR: Too many arguments.${reset}"
	exit 1
fi

# List of all the valid theme names
valid_themes=(
	"ayu-dark"
	"ayu-mirage"
	"ayu-light"
	"gruvbox-dark"
	"gruvbox-light"
	"onehalf-dark"
	"onehalf-light"
	"dracula"
	"nord"
)

# Make sure the theme name is valid
is_valid_theme_name=0

for theme in "${valid_themes[@]}"; do
	if [[ "$1" == "$theme" ]]; then
		is_valid_theme_name=1
	fi
done

if [[ ! $is_valid_theme_name ]]; then
	echo -e "${red}${bold}ERROR: Invalid theme name.${reset}"
	exit 1
fi

# Important directory references
vim_theme=~/.config/vim/theme.vim
neovim_theme=~/.config/nvim/lua/theme.lua
emacs_theme=~/.emacs.d/lisp/theme.el
alacritty_theme_dir=~/.config/.alacritty/themes
alacritty_theme=~/.config/.alacritty/themes/theme.yml
alacritty_config=~/.alacritty.yml
rofi_theme=~/.config/rofi/theme.rasi
awesomewm_theme=~/.config/awesome/ui/theme.lua

if [[ $1 == "ayu-dark" ]]; then
	# Change Vim
	echo "set background=dark" > "$vim_theme"
	echo 'let g:ayucolor="dark"' >> "$vim_theme"
	echo "colorscheme ayu" >> "$vim_theme"

	# Change NeoVim
	echo 'vim.go.background = "dark"' > "$neovim_theme"
	echo 'require("ayu").colorscheme()' >> "$neovim_theme"
elif [[ $1 == "ayu-mirage" ]]; then
	# Change Vim
	echo "set background=dark" > "$vim_theme"
	echo 'let g:ayucolor="mirage"' >> "$vim_theme"
	echo "colorscheme ayu" >> "$vim_theme"

	# Change NeoVim
	echo 'vim.go.background = "dark"' > "$neovim_theme"
	echo 'require("ayu").setup({ mirage = true })' >> "$neovim_theme"
	echo 'require("ayu").colorscheme()' >> "$neovim_theme"
elif [[ $1 == "ayu-light" ]]; then
	# Change Vim
	echo "set background=light" > "$vim_theme"
	echo "colorscheme ayu" >> "$vim_theme"

	# Change NeoVim
	echo 'vim.go.background = "light"' > "$neovim_theme"
	echo 'require("ayu").colorscheme()' >> "$neovim_theme"
elif [[ $1 == "gruvbox-dark" ]]; then
	# Change Vim
	echo "colorscheme gruvbox" > "$vim_theme"
	echo "set background=dark" >> "$vim_theme"

	# Change NeoVim
	echo "vim.cmd \"colorscheme gruvbox\"" > "$neovim_theme"
	echo "vim.go.background = \"dark\"" >> "$neovim_theme"

	# Change Emacs
	# echo "(load-theme 'doom-gruvbox t)" > "$emacs_theme"
elif [[ $1 == "gruvbox-light" ]]; then
	# Change Vim
	echo "colorscheme gruvbox" > "$vim_theme"
	echo "set background=light" >> "$vim_theme"

	# Change NeoVim
	echo "vim.cmd \"colorscheme gruvbox\"" > "$neovim_theme"
	echo "vim.go.background = \"light\"" >> "$neovim_theme"

	# Change Emacs
	# echo "(load-theme 'doom-gruvbox-light t)" > "$emacs_theme"
elif [[ $1 == "onehalf-dark" ]]; then
	# Change Vim
	echo "colorscheme onehalfdark" > "$vim_theme"

	# Change NeoVim
	echo "vim.cmd \"colorscheme onehalfdark\"" > "$neovim_theme"

	# Change Emacs
	# echo "(load-theme 'doom-one t)" > "$emacs_theme"
elif [[ $1 == "onehalf-light" ]]; then
	# Change Vim
	echo "colorscheme onehalflight" > "$vim_theme"

	# Change NeoVim
	echo "vim.cmd \"colorscheme onehalflight\"" > "$neovim_theme"

	# Change Emacs
	# echo "(load-theme 'doom-one-light t)" > "$emacs_theme"
elif [[ $1 == "dracula" ]]; then
	# Change Vim
	echo "colorscheme dracula" > "$vim_theme"

	# Change NeoVim
	echo "vim.cmd \"colorscheme dracula\"" > "$neovim_theme"

	# Change Emacs
	# echo "(load-theme 'doom-dracula t)" > "$emacs_theme"
elif [[ $1 == "nord" ]]; then
	# Change Vim
	echo "colorscheme nord" > "$vim_theme"

	# Change NeoVim
	echo "vim.cmd \"colorscheme nord\"" > "$neovim_theme"

	# Change Emacs
	# echo "(load-theme 'doom-nord t)" > "$emacs_theme"
fi

# Change Alacritty
echo "import:" > "$alacritty_theme"
echo "  - $alacritty_theme_dir/$1.yml" >> "$alacritty_theme"
touch "$alacritty_config" # Reload alacritty open windows

# Change Rofi
echo "@theme \"$1\"" > "$rofi_theme"

# Change AwesomeWM
echo "return require(\"ui.themes.$1.theme\")" > "$awesomewm_theme"

echo -e "${green}${bold}Theme changed to $1 successfully.${reset}"
