#!/bin/sh

: '
dmux - Directory Tmux

Create a Tmux session with the name of the current directory (if not already exists) and attach to it.

Based on: https://github.com/thoughtbot/dotfiles/blob/master/bin/tat
'

path_name="$(basename "$PWD" | tr . -)"
session_name=${1-$path_name}

in_tmux() {
	# If we are inside Tmux then the TMUX variable should be set.
	[ -n "$TMUX" ]
}

session_exists() {
	tmux has-session -t "=$session_name"
}

create_detached_session() {
	(TMUX='' tmux -u new-session -Ad -s "$session_name")
}

create_if_needed_and_attach() {
	if ! in_tmux; then
		tmux -u new-session -As "$session_name"
	else
		if ! session_exists; then
			create_detached_session
		fi
		tmux switch-client -t "$session_name"
	fi
}

create_if_needed_and_attach
