{
  system,
  hostId,
  diskEncryptionKeyFile,
  persistDirBackup,
  persistDirNoBackup,
  ...
}: {
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    (modulesPath + "/profiles/qemu-guest.nix")
    (import ./disko.nix {
      inherit hostId diskEncryptionKeyFile persistDirBackup persistDirNoBackup;
    })
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "virtio_pci" "virtio_scsi" "usbhid" "sr_mod"];

  boot.kernelModules = [];
  boot.extraModulePackages = [];

  # NOTE: Not generated by `nixos-generate-config`.
  # Based on: https://discourse.nixos.org/t/nixos-on-hetzner-cloud-arm/29186/6

  # Workaround because console defaults to serial.
  boot.kernelParams = ["console=tty"];
  # Initialize the display early to get a complete log.
  boot.initrd.kernelModules = ["virtio_gpu"];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault system;

  # Bootloader
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
}
