#!/bin/bash

: '
tmux-clock - Clock for TMUX status bar
'

# Colors
bold="#[bold]"
white_fg="#[fg=white]"
black_fg="#[fg=black]"
green_bg="#[bg=green]"
yellow_bg="#[bg=yellow]"
blue_bg="#[bg=blue]"
cyan_bg="#[bg=cyan]"
red_bg="#[bg=red]"
reset="#[default]"

# Get Time
time=$(date +'%H:%M')
echo $time

color="$cyan_bg$black_fg"

printf "%s" "$color"
printf "%-16s" " 🕜 $time "
printf "%s" "$reset"
