#!/bin/bash

: '
tmux-used-ram-percentage - Monitor RAM usage in TMUX
'

# Colors
bold="#[bold]"
white_fg="#[fg=white]"
black_fg="#[fg=black]"
green_bg="#[bg=green]"
yellow_bg="#[bg=yellow]"
red_bg="#[bg=red]"
reset="#[default]"

# Usage Levels
low=70
medium=90

# Actual current value
used_ram_percentage=$(free | grep Mem | awk '{ printf("%.2f\n", $3/$2 * 100.0) }')

# Default state is high state
color="$red_bg$white_fg$bold"

# Change state as needed
if (( $(bc <<< "$used_ram_percentage <= $low") )); then
	color="$green_bg$black_fg"
elif (( $(bc <<< "$used_ram_percentage <= $medium") )); then
	color="$yellow_bg$black_fg"
fi

printf "%s" "$color"
printf "%-14s" " RAM: $used_ram_percentage% "
printf "%s" "$reset"
