#!/bin/bash

: '
tmux-connectivity-status - Monitor connectivity status in TMUX
'

# Colors
bold="#[bold]"
white_fg="#[fg=white]"
black_fg="#[fg=black]"
green_bg="#[bg=green]"
yellow_bg="#[bg=yellow]"
blue_bg="#[bg=blue]"
red_bg="#[bg=red]"
reset="#[default]"

# Usage Levels
low=50
medium=75

# Check connectivity with ping
# Redirect output to /dev/null since we don't want it
# Also redirect stderr to stdout
ping -c1 www.google.com -W 2 > /dev/null 2>&1

status="$?"

# Default state is disconnected
color="$red_bg$white_fg$bold"
msg="Disconnected"

# If connected change state
if [[ "$status" == "0" ]]; then
	color="$yellow_bg$black_fg"
	msg="Connected"
fi

printf "%s" "$color"
printf "%-14s" " $msg "
printf "%s" "$reset"
